server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
spring:
  cloud:
    loadbalancer:
      nacos:
        enabled: true # 启用 Nacos 负载均衡
      configurations: default # 默认配置
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: public
        username: nacos
        password: nacos
      discovery:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
        namespace: public
        # 与conf/application.properties中的配置一致,用于服务发现时携带元数据信息,便于权限控制
        metadata:
          nacos.core.auth.server.identity.key: sfxsKey
          nacos.core.auth.server.identity.value: sfxsValue
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true # Enable dynamic routing based on service discovery
          lower-case-service-id: true # Use lowercase service IDs
      routes:
        - id: api-service
          uri: lb://api-service # Use Nacos service ID
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1 # Remove /api-service from the path
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
