management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: public
        username: nacos
        password: nacos
      discovery:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
        namespace: public
        # 与conf/application.properties中的配置一致,用于服务发现时携带元数据信息,便于权限控制
        metadata:
          nacos.core.auth.server.identity.key: sfxsKey
          nacos.core.auth.server.identity.value: sfxsValue
        username: nacos
        password: nacos

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
aliyunOss:
  file:
    subDir: dev/sfxs